#! /usr/bin/env python

import btsma
import btsmaconfig

inverters = btsmaconfig.read_config()

for inv in inverters:
    print("%s:" % inv.name)

    sma = inv.connect_and_logon()

    dtime, daily = sma.daily_yield()
    print("\tDaily generation at %s:\t%d Wh"
          % (btsma.format_time(dtime), daily))

    ttime, total = sma.total_yield()
    print("\tTotal generation at %s:\t%d Wh"
          % (btsma.format_time(ttime), total))
