#! /usr/bin/env python
#
# sma2-status - Show current status of SMA inverters
# Copyright (C) 2014 David Gibson <david@gibson.dropbear.id.au>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

from __future__ import print_function

import smadata2.protocol
import smadata2.config
from smadata2.util import format_time

config = smadata2.config.SMAData2Config()

for inv in config.inverters():
    print("%s:" % inv.name)

    sma = inv.connect_and_logon()

    dtime, daily = sma.daily_yield()
    print("\tDaily generation at %s:\t%d Wh" % (format_time(dtime), daily))

    ttime, total = sma.total_yield()
    print("\tTotal generation at %s:\t%d Wh" % (format_time(ttime), total))
