#! /usr/bin/env python
#
# sma2-download - Download historic generation info from SMA inverters
# Copyright (C) 2014 David Gibson <david@gibson.dropbear.id.au>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import time

import smadata2.protocol
import smadata2.util
import smadata2.config
import smadata2.db

config = smadata2.config.SMAData2Config()
db = smadata2.db.SMADatabaseSQLiteV0(config.dbname)

for inv in config.inverters():
    print("%s (SN: %d)" % (inv.name, inv.serial))

    lasttime = db.get_last_historic(inv.serial)
    if lasttime is None:
        lasttime = inv.starttime

    now = int(time.time())

    print("Retrieving data from %s to %s"
          % (smadata2.util.format_time(lasttime), smadata2.util.format_time(now)))

    sma = inv.connect_and_logon()

    data = sma.historic(lasttime+1, now)
    if len(data):
        print("Downloaded %d observations from %s to %s"
              % (len(data), smadata2.util.format_time(data[0][0]),
                 smadata2.util.format_time(data[-1][0])))
    else:
        print("No new data")

    for timestamp, total in data:
        if total == 0xffffffff:
            continue
        db.add_historic(inv.serial, timestamp, total)

    db.commit()
