#! /usr/bin/env python

import smadata2.protocol
import smadata2.config
from smadata2.util import format_time

config = smadata2.config.SMAData2Config()

for inv in config.inverters():
    print("%s:" % inv.name)

    sma = inv.connect_and_logon()

    dtime, daily = sma.daily_yield()
    print("\tDaily generation at %s:\t%d Wh" % (format_time(dtime), daily))

    ttime, total = sma.total_yield()
    print("\tTotal generation at %s:\t%d Wh" % (format_time(ttime), total))
